# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-18 09:04
from __future__ import unicode_literals

import SWZL.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='信息标题:')),
                ('lost_type', models.CharField(choices=[('wallet', '钱包'), ('key', '钥匙'), ('card', '卡类/证照'), ('electric', '数码产品'), ('bag', '手袋/挎包'), ('clothes', '衣服/鞋帽'), ('book', '书籍/文件'), ('others', '其它')], default='choice', max_length=32, verbose_name='失物类别:')),
                ('pub_time', models.DateTimeField(auto_now=True, verbose_name='发布的时间:')),
                ('lost_time', models.CharField(max_length=64, verbose_name='丢失时间:')),
                ('lost_place', models.CharField(max_length=64, verbose_name='丢失的地点')),
                ('status', models.CharField(choices=[('unreviewed', '未审核'), ('finding', '寻找中'), ('found', '已找到')], default='unreviewed', max_length=32, verbose_name='信息的状态:')),
                ('detailed_description', models.TextField(blank=True, null=True, verbose_name='详细描述:')),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='物品图片:')),
                ('contact', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人')),
                ('qq', models.IntegerField(verbose_name='QQ')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(max_length=64, verbose_name='联系地址')),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='信息标题:')),
                ('lost_type', models.CharField(choices=[('wallet', '钱包'), ('key', '钥匙'), ('card', '卡类/证照'), ('electric', '数码产品'), ('bag', '手袋/挎包'), ('clothes', '衣服/鞋帽'), ('book', '书籍/文件'), ('others', '其它')], default='choice', max_length=32, verbose_name='拾取类别:')),
                ('pub_time', models.DateTimeField(auto_now=True, verbose_name='发布的时间:')),
                ('lost_time', models.CharField(max_length=64, verbose_name='拾取时间:')),
                ('lost_place', models.CharField(max_length=64, verbose_name='拾取的地点')),
                ('status', models.CharField(choices=[('unreviewed', '未审核'), ('finding', '寻找中'), ('found', '已找到')], default='unreviewed', max_length=32, verbose_name='信息的状态:')),
                ('is_recruitment', models.BooleanField(default=True)),
                ('detailed_description', models.TextField(blank=True, null=True, verbose_name='详细描述:')),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='物品图片:')),
                ('contact', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人')),
                ('qq', models.IntegerField(verbose_name='QQ')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(max_length=64, verbose_name='联系地址')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.EmailField(max_length=255, unique=True, verbose_name='用户名')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_admin', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('mobile', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='手机')),
                ('memo', models.TextField(blank=True, default=None, null=True, verbose_name='备注')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '账户信息',
                'verbose_name': '账户信息',
            },
            managers=[
                ('objects', SWZL.models.UserManager()),
            ],
        ),
    ]
