# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-22 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SWZL', '0003_auto_20190422_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='announcer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='announcer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
